language: node_js
node_js:
  - node

addons:
  apt:
    packages:
      - xvfb

before_install:
  - npm i -g pnpm

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - pnpm i
